name: Build and Push Containers
# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push-container-ci-cd:
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'Build CI-CD Container')"
    name: 'Build and Push Container CI-CD'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

    - name: 'Build and Push Container CI-CD'
      run: |
        cp build/Dockerfile.ci-cd Dockerfile.ci-cd
        gcloud builds submit --config build/cloudbuild-ci-cd.yaml --substitutions _GOOGLE_CLOUD_REGION=us-central1,_GOOGLE_CLOUD_PROJECT=tfdf-mlops,_DOCKER_REPO_NAME=docker-repo
      
  build-push-container-tfx-vertex:
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'Build TFX Vertex Container')"
    name: 'Build and Push Container TFX Vertex'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
         
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

    - name: 'Build and Push Container TFX Vertex'
      run: |
        cp build/Dockerfile.vertex Dockerfile.vertex
        gcloud builds submit --config build/cloudbuild-vertex.yaml --substitutions _GOOGLE_CLOUD_REGION=us-central1,_GOOGLE_CLOUD_PROJECT=tfdf-mlops,_DOCKER_REPO_NAME=docker-repo
