name: Compile Pipeline
# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-pipeline:
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'Deploy Pipeline')"
    name: 'Compile Vertex AI pipeline'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
         
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

    - name: 'Deploy Vertex AI Pipeline'
      run: gcloud builds submit --no-source --config build/cloudbuild-deploy-pipeline.yaml --project tfdf-mlops --region us-central1